import './globals.css';

import { css } from '@style/css';
import { PhilosopherBold, PirataOne } from 'styles/font';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${PirataOne.variable} ${PhilosopherBold.variable}`}
    >
      <body
        className={css({
          p: 2,
          fontFamily: 'pirataOne',
          backgroundColor: 'black',
          color: 'white',
        })}
      >
        {children}
      </body>
    </html>
  );
}
